name: flutter_super_hero
description: Flutter is a Super Hero.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  database:
    path: database
  shared:
    path: shared
  domain:
    path: domain
  network:
    path: network
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get_it: ^7.2.0
  flutter_bloc: ^8.0.0
  freezed: ^1.0.2
  palette_generator: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.2

flutter:
  uses-material-design: true
