name: network
description: Super Hero Network.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  shared:
    path: ../shared
  flutter:
    sdk: flutter
  dio: ^4.0.4
  json_serializable: ^6.1.1
  build_runner: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
