name: domain
description: Super Hero Domain
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  database:
    path: ../database
  network:
    path: ../network
  shared:
    path: ../shared
  flutter:
    sdk: flutter
  get_it: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
