name: database
description: Database for Super Heroes.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  shared:
    path: ../shared
  flutter:
    sdk: flutter
  floor: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  floor_generator: ^1.2.0
  build_runner: ^2.1.2

flutter:
